version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.8"

python:
  install:
    - requirements: docs/source/requirements.txt
    # Install our python package before building the docs
    # - method: pip
    #   path: .

sphinx:
  configuration: docs/source/conf.py
  # fail_on_warning: true
  