CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 torchrun --nproc_per_node 8 \
retrieval.py \
            --batch_size           128 \
            --dataset              inat \
            --debug                0 \
            --epochs               128 \
            --lr                   4e-05 \
            --lr_pfc_weight        10.0 \
            --input_size           224 \
            --gradient_acc         1 \
            --model_name           ViT-B/16 \
            --margin_loss_m1       1.0 \
            --margin_loss_m2       0.35 \
            --margin_loss_m3       0.0 \
            --margin_loss_s        32.0 \
            --margin_loss_filter   0.0 \
            --num_workers          4 \
            --num_feat             512 \
            --optimizer            adamw \
            --output_dim           768 \
            --output               /tmp/tmp_for_training \
            --resume               NULL \
            --sample_rate          1.0 \
            --seed                 1024 \
            --transform            timm \
            --weight_decay         0 2>&1 | tee inat_b16_v2.log
